TeamOPSchoolCupWeb/TeamOPSchoolCup.Web/Controllers/NSSFController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TeamOPSchoolCup.Domain.POCO;
using TeamOPSchoolCup.Domain.DAL;
using TeamOPSchoolCup.Domain.Services;
using TeamOPSchoolCup.Domain.DTO;
using TeamOPSchoolCup.Domain.Resources;
using System.Web.Security;
using TeamOPSchoolCup.Domain.Exceptions;

namespace TeamOPSchoolCup.Web.Controllers
{
  public class NSSFController : Controller
  {

    //
    // GET: /NSSF/

    public ViewResult Index() {
      var nssfs = NSSFService.GetNSSFs().ToList();
      return View(nssfs);
    }

    //
    // GET: /NSSF/Details/5

    public ViewResult Details(int nssfid) {
      NSSF nssf = NSSFService.GetNSSF(nssfid: nssfid);
      return View(nssf);
    }

    //
    // GET: /NSSF/Create
    [Authorize(Roles = "ISFAdmin")]
    public ActionResult Create() {
      if (Roles.IsUserInRole(User.Identity.Name, "Inactive")) { throw new TeamOPSchoolCupException(ErrorStrings.NoPermissionInactive); }
      ViewBag.RegionId = new SelectList(RegionService.GetStructuredRegions(), "RegionId", "Name");
      return View();
    }
      
    //
    // POST: /NSSF/Create

    [HttpPost]
    [Authorize(Roles = "ISFAdmin")]
    public ActionResult Create(NSSFRegion nssfregion) {
      if (Roles.IsUserInRole(User.Identity.Name, "Inactive")) { throw new TeamOPSchoolCupException(ErrorStrings.NoPermissionInactive); }
      if (ModelState.IsValid) {
        Region region = RegionService.GetRegion(nssfregion.RegionId);
        NSSF nssf = new NSSF
        {
          Name = nssfregion.Name,
          City = nssfregion.City,
          Street = nssfregion.Street,
          Country = nssfregion.Country,
          PhoneNumber = nssfregion.PhoneNumber,
          FaxNumber = nssfregion.FaxNumber,
          DateAdded = DateTime.Now,
          Zipcode = nssfregion.Zipcode,
          Email = nssfregion.Email,
          Region = region
        };
        NSSFService.AddNSSF(nssf);
        string body = string.Format("{0}{1}{2}{3}{4}", MailStrings.DefaultAnonGreeting, MailStrings.DefaultAutomatedWarning, string.Format(MailStrings.NSSFAdded, "http://localhost:61513/en/Member/AddNSSFRep?nssfemail=" + nssfregion.Email /*Url.Action("AddNSSFRep", "Member")*/), MailStrings.DefaultWrongAction, MailStrings.DefaultSignoff);
        MailService.SendMail(MailStrings.SubjectNSSFAdded, new List<string>() { nssf.Email }, body, true);


        return RedirectToAction("Index");
      }
      ViewBag.RegionId = new SelectList(RegionService.GetStructuredRegions(), "RegionId", "Name");

      return View(nssfregion);
    }

    //
    // GET: /NSSF/Edit/5
    [Authorize(Roles = "NSSFRep")]
    public ActionResult Edit(int? nssfid) {
      if (Roles.IsUserInRole(User.Identity.Name, "Inactive")) { throw new TeamOPSchoolCupException(ErrorStrings.NoPermissionInactive); }
      NSSF nssf = NSSFService.GetNSSF(nssfid: nssfid);
      NSSFRegion nssfregion = new NSSFRegion
      {
        Name = nssf.Name,
        City = nssf.City,
        Street = nssf.Street,
        Country = nssf.Country,
        PhoneNumber = nssf.PhoneNumber,
        FaxNumber = nssf.FaxNumber,
        Zipcode = nssf.Zipcode,
        Email = nssf.Email,
        RegionId = nssf.Region.RegionId
      };
      ViewBag.RegionId = new SelectList(RegionService.GetStructuredRegions(), "RegionId", "Name");
      return View(nssfregion);
    }

    //
    // POST: /NSSF/Edit/5

    [HttpPost]
    [Authorize(Roles = "NSSFRep")]
    public ActionResult Edit(NSSFRegion nssfregion) {
      if (Roles.IsUserInRole(User.Identity.Name, "Inactive")) { throw new TeamOPSchoolCupException(ErrorStrings.NoPermissionInactive); }
      if (ModelState.IsValid) {
        //NSSF nssf = new NSSF
        //{
        //  Name = nssfregion.Name,
        //  City = nssfregion.City,
        //  Street = nssfregion.Street,
        //  Country = nssfregion.Country,
        //  PhoneNumber = nssfregion.PhoneNumber,
        //  FaxNumber = nssfregion.FaxNumber,
        //  DateAdded = DateTime.Now,
        //  Zipcode = nssfregion.Zipcode,
        //  Email = nssfregion.Email,
        //  Region = RegionService.GetRegion(nssfregion.RegionId)
        //};
        NSSF nssf = NSSFService.GetNSSF(name: nssfregion.Name,email:nssfregion.Email);
        nssf.Name = nssfregion.Name;
        nssf.City = nssfregion.City;
        nssf.Street = nssfregion.Street;
        nssf.Country = nssfregion.Country;
        nssf.PhoneNumber = nssfregion.PhoneNumber;
        nssf.FaxNumber = nssfregion.FaxNumber;
        nssf.Zipcode = nssfregion.Zipcode;
        nssf.Email = nssfregion.Email;
        nssf.Region = NSSFService.GetRegion(nssf);

        NSSFService.UpdateNSSF(nssf);
        return RedirectToAction("Index","Administration");
      }
      ViewBag.RegionId = new SelectList(RegionService.GetStructuredRegions(), "RegionId", "Name");
      return View(nssfregion);
    }

  }
}

TeamOPSchoolCupWeb/TeamOPSchoolCup.Web/Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TeamOPSchoolCup.Domain.POCO;
using TeamOPSchoolCup.Domain.DAL;
using TeamOPSchoolCup.Domain.DTO;
using TeamOPSchoolCup.Domain.POCO.Members;
using TeamOPSchoolCup.Domain.Services;
using TeamOPSchoolCup.Domain.POCO.Ranking;
using System.IO;
using TeamOPSchoolCup.Web.Helpers;
using System.Web.Script.Serialization;
using System.Web.Security;
using TeamOPSchoolCup.Domain.Resources;
using TeamOPSchoolCup.Domain.Exceptions;

namespace TeamOPSchoolCup.Web.Controllers
{
  public class TeamController : Controller
  {

    public ViewResult Profile(int id) {
      Team team = TeamService.GetTeam(id);
      ViewBag.teamRankings = RankingService.GetRankings(team);
      ViewBag.teamMembers = TeamService.GetTeamMemberships(team, null, TeamService.Historicality.CURRENT);
      string photoPath = "~/Upload/Teampicture/"+id+".jpeg";
      string photoPathTest = Server.MapPath("~/Upload/Teampicture/" + id + ".jpeg");
      string logoPath = "~/Upload/Teamlogo/" + id + ".jpeg";
      string logoPathTest = Server.MapPath("~/Upload/Teamlogo/" + id + ".jpeg");      
      ViewBag.photopath = photoPath;
      ViewBag.photopathTest = photoPathTest;
      ViewBag.logopath = logoPath;
      ViewBag.logopathTest = logoPathTest;
      return View(team);

    }
    public ActionResult TeamResults(int teamId)
    {
      int year = DateTime.Today.Year;
      Team team = TeamService.GetTeam(teamId);
      List<Event> events = EventService.GetEvents(teamId: teamId);
      List<Result> results = ResultService.GetResults(team: team);
                
      TeamComparison.StudentsInTeamsWithEvents teamData = new TeamComparison.StudentsInTeamsWithEvents();
      teamData.TeamId = team.TeamId;
      teamData.Name = team.Name;
      foreach (TeamMembership tm1 in TeamService.GetTeamMemberships(team))
      {
        TeamComparison.StudentsParticipatingEvents spe = new TeamComparison.StudentsParticipatingEvents();
        spe.Id = tm1.MemberId;
        spe.Name = tm1.Student.Member.Name;
        events.ForEach(x => spe.ParticipatingEvents.Add(x.Name, EventService.GetEvents(tm1.MemberId).Select(y => y.EventId).Contains(x.EventId)));
        teamData.Students.Add(spe);
      }

     
      List<TeamComparison.StudentsInTeamsWithEvents> data = new List<TeamComparison.StudentsInTeamsWithEvents>();
      data.Add(teamData);
      ViewBag.StudentsInTeamsWithEventsData = data;
      ViewBag.Sports = new SelectList(SportService.GetSports(true), "SportId", "Name");
      ViewBag.Meetings = new SelectList(MeetingService.GetMeetings(team: team), "MeetingId", "Name");
      ViewBag.Events = new SelectList(EventService.GetEventsOfMeeting(MeetingService.GetMeeting(4)), "EventId", "Name");
                
      ViewBag.StudentsInTeamsWithEvents = new JavaScriptSerializer().Serialize(data);
      return View(results);
    }
    public ActionResult LoadTeamResult(int teamId, bool? official, int? sportId, int? meetingId, int? pEventId, int? page, int? pageSize)
    {
      int pageSizeValue = pageSize.HasValue ? pageSize.Value : 5; // CHANGE THIS LINE IF YOU LOVE LOGIC
      // Parameters

      List<Result> mr = ResultService.GetTeamResults(teamId, official, sportId, meetingId, pEventId);

      var paginatedMR = new PaginatedList<Result>(mr.ToList(), page ?? 0, pageSizeValue);

      return PartialView("Partials/_TeamResultsTable", paginatedMR);
    }
    [Authorize(Roles="Student,Coach")]
    public ActionResult Dashboard(int id) {
      Team team = TeamService.GetTeam(id);
      Member m = MemberService.GetMember(email: User.Identity.Name);

      if (m.Coach != null)
      {
        if (!m.Coach.TeamCoaches.Select(x => x.TeamId).Contains(team.TeamId)) throw new TeamOPSchoolCupException(ErrorStrings.Team_Dashboard_CoachNoAccess);
        ViewBag.StudCoach = false;
      }
      else if (m.Student != null)
      {
        if (!m.Student.TeamMemberShips.Select(x => x.TeamId).Contains(team.TeamId)) throw new TeamOPSchoolCupException(ErrorStrings.Team_Dashboard_StudentNoAccess);
        ViewBag.StudCoach = true;
      }

      ViewBag.BestTeamResult = RankingService.GetBestTeamResult(team,DateTime.Today.Year);
      ViewBag.Topics = ConversationService.GetTopicsOfTeam(team, true);
      ViewBag.UserId = m.MemberId;
      ViewBag.TeamRankings = RankingService.GetRankings(team);
      ViewBag.LatestTopicMessage = ConversationService.GetFirstMessage(ConversationService.GetLatestSpotlightTopic(team));
      return View(team);
    }

    public ActionResult Topic(int id) {
      Topic topic = ConversationService.GetTopic(id);
      ViewBag.Topics = ConversationService.GetTopicsOfTeam(topic.Team, true);
      ViewBag.Messages = ConversationService.GetMessagesOfTopic(id);
      ViewBag.Topic = topic;
      Message message = new Message();
      message.TopicId = topic.TopicId;
      return View(message);
    }

    [HttpPost]
    public ActionResult Topic(Message message) {
      if (Roles.IsUserInRole(User.Identity.Name, "Inactive")) { throw new TeamOPSchoolCupException(ErrorStrings.Member_Inactive_NoAccess); }
      if (ModelState.IsValid) {
        if (User.Identity.IsAuthenticated) {
          Member m = MemberService.GetMember(email: User.Identity.Name);
          if (m.Student != null || m.Coach != null) {
            message.DatePosted = DateTime.Now;
            if (m.Student != null && m.Coach == null) {
              ConversationService.AddMessage(message, studentId: m.MemberId, topicId: message.TopicId);
            }
            else {
              ConversationService.AddMessage(message, coachId: m.MemberId, topicId: message.TopicId);
            }
          }
        }
      }
      return RedirectToAction("Topic", new { id = message.TopicId });
    }

    //
    // GET: /Team/Create

    public ActionResult Create() {
      if (Roles.IsUserInRole(User.Identity.Name, "Inactive")) { throw new TeamOPSchoolCupException(ErrorStrings.NoPermissionInactive); }
      ViewBag.SportId = new SelectList(SportService.GetSports(true), "SportId", "Name");
      return View();
    }

    //
    // POST: /Team/Create

    [HttpPost]
    public ActionResult Create(Team team, HttpPostedFileBase Logo, HttpPostedFileBase Photo) {
      if (Roles.IsUserInRole(User.Identity.Name, "Inactive")) { throw new TeamOPSchoolCupException(ErrorStrings.NoPermissionInactive); }
      if (ModelState.IsValid) {
        Coach coach = MemberService.GetCoach(MemberService.GetMember(email: User.Identity.Name).MemberId);
        
        team.SchoolId = coach.SchoolId;

        TeamService.AddTeam(team);

        if (Photo != null && Logo != null
          && Photo.ContentLength > 0 && Logo.ContentLength > 0) {
          new ImageHelper().Save(new System.Drawing.Bitmap(Photo.InputStream), 180, 130, 80, Path.Combine(Server.MapPath("~/Upload/Teampicture"), "" + team.TeamId + ".jpeg"));
          new ImageHelper().Save(new System.Drawing.Bitmap(Logo.InputStream), 100, 100, 80, Path.Combine(Server.MapPath("~/Upload/Teamlogo"), "" + team.TeamId + ".jpeg"));
        }
        if (Photo != null &&Photo.ContentLength > 0
                  && Logo == null) {
          new ImageHelper().Save(new System.Drawing.Bitmap(Photo.InputStream), 180, 130, 80, Path.Combine(Server.MapPath("~/Upload/Teampicture"), "" + team.TeamId + ".jpeg"));
        }
        if (Photo == null
                && Logo != null && Logo.ContentLength > 0) {
          new ImageHelper().Save(new System.Drawing.Bitmap(Logo.InputStream), 180, 130, 80, Path.Combine(Server.MapPath("~/Upload/Teamlogo"), "" + team.TeamId + ".jpeg"));
        }

        if (!MemberService.AddCoachToTeam(coach.MemberId, team.TeamId))
        {
          throw new Exception();
        }
        
      }
     return RedirectToAction("SchoolCup", "SchoolCup");
    }

    [Authorize(Roles="Coach")]
    public ActionResult AddTeamMembership(int id) {
      if (Roles.IsUserInRole(User.Identity.Name, "Inactive")) { throw new TeamOPSchoolCupException(ErrorStrings.AddTeamMembership_NoPermission); }
      Team t = TeamService.GetTeam(id: id);
      if (t.TeamCoaches.Single(tc => tc.DateLeft >= DateTime.Today).MemberId != MemberService.GetMember(email: User.Identity.Name).MemberId) { throw new TeamOPSchoolCupException(ErrorStrings.Result_CantAddResultsToMeeting); /*TODO ERROR*/ }
      List<Student> students = TeamService.GetPotentialTeamMembers(t);
      ViewBag.Team = t;
      return View(students);
    }

    //[HttpPost]
    [Authorize(Roles = "Coach")]
    public ActionResult ActualAddTeamMembership(int teamId, Guid studentId)
    {
      if (Roles.IsUserInRole(User.Identity.Name, "Inactive")) { throw new TeamOPSchoolCupException(ErrorStrings.Result_CantAddResultsToMeeting); }
      if (TeamService.AddTeamMembership(teamId, studentId)) {
        return RedirectToAction("AddTeamMembership", new { id = teamId });
      }
      else { throw new TeamOPSchoolCupException(ErrorStrings.Result_CantAddResultsToMeeting); }
    }

    [Authorize(Roles="Coach")]
    public ActionResult TeamManagement(int id) {
      Team team = TeamService.GetTeam(id);
      if (User.Identity.IsAuthenticated) {
        Member m = MemberService.GetMember(email:User.Identity.Name);
        if (m.Coach != null)
        {
          if (!m.Coach.TeamCoaches.Select(x => x.TeamId).Contains(team.TeamId)) throw new TeamOPSchoolCupException(ErrorStrings.Team_Dashboard_CoachNoAccess);
          ViewBag.StudCoach = false;
        }
        if (m.Student != null || m.Coach != null) {
          if (m.Student != null && m.Coach == null) {
            ViewBag.StudCoach = true;
          }
          else {
            ViewBag.StudCoach = false;
          }
        }
      }
      EditableTeam edTeam = new EditableTeam(team);

      return View(edTeam);
    }

    [HttpPost]
    public ActionResult TeamManagement(EditableTeam eteam) {

TeamOPSchoolCupWeb/TeamOPSchoolCup.Web/Views/Member/AddCoach.cshtml
@model TeamOPSchoolCup.Domain.DTO.BasicMemberInfo
@using TeamOPSchoolCup.Domain.DTO
@using TeamOPSchoolCup.Domain.Resources
@{
    ViewBag.Title = @MemberString.AddCoach;
}
@section region{
    <link rel="Stylesheet" href="@Url.Content("~/Content/css/Administration.css")" type="text/css" />
}
<h2 class="wrappertitel">@ViewBag.Title</h2>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

<div id="content-form">
@using (Html.BeginForm("AddCoach", "Member", new { schoolId = ViewBag.School.SchoolId }))
{
    @Html.ValidationSummary(true)
    <table>
        <tr class="crud_row">
            <td class="number">@Html.LabelFor(model => model.Name)
            </td>
            <td>
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </td>
        </tr>
        <tr class="crud_row">
            <td class="number">@Html.LabelFor(model => model.Email)
            </td>
            <td>
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </td>
        </tr>
        <tr class="crud_row">
            <td class="number">@Html.LabelFor(model => model.Gender)
            </td>
           <td id="genderSelect">
                @{List<Gender> genders = new List<Gender>();
                  foreach(Gender g in Enum.GetValues(typeof(TeamOPSchoolCup.Domain.DTO.Gender)))
                  { 
                      if(!g.Equals(Gender.UNISEX)){
                      genders.Add(g);}
                  }}
                @Html.DropDownListFor(model => model.Gender, new SelectList(genders))
                @Html.ValidationMessageFor(model => model.Gender)
            </td>
        </tr>
        <tr>
            <td>
                <a class="return" href="@Url.Action("Index","Administration")">
                    <img src="@Url.Content("~/Content/Images/return_button.png")", alt="Back" />
                    <span>Back</span> </a>
            </td>
            <td class="crud_submit">
                <input id="derp" type="submit" value="Create" />
            </td>
        </tr>
        </table>
}
</div>

TeamOPSchoolCupWeb/TeamOPSchoolCup.Web/Views/Member/AddMembersToASPNETAndShowPassword.cshtml
@{
    ViewBag.Title = "AddMembersToASPNETAndShowPassword";
}

<h2>AddMembersToASPNETAndShowPassword</h2>
<h3>Users</h3>
@foreach(KeyValuePair<string,string> kvp in ViewBag.Users){
    <p>Username: @kvp.Key</p>
    <p>password: @kvp.Value</p>
    
}
<h3>UserIds</h3>
@foreach(KeyValuePair<string,string> kvp in ViewBag.UserIds){
    <p>Member name: @kvp.Key</p>
    <p>userId: @kvp.Value</p>
    
}

TeamOPSchoolCupWeb/TeamOPSchoolCup.Web/Views/Member/AddNSSFRep.cshtml
@model TeamOPSchoolCup.Domain.DTO.BasicMemberInfo
@using TeamOPSchoolCup.Domain.DTO;
@{
    ViewBag.Title = "addNSSFRep";
}
@section region{
    <link rel="Stylesheet" href="@Url.Content("~/Content/css/Administration.css")" type="text/css" />
}

<h2 class="wrappertitel">
    addNSSFRep</h2>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<div id="content-form">
    @using (Html.BeginForm("AddNSSFRep", "Member", new { nssfid = ViewBag.NSSFId }, FormMethod.Post))
    {    
        @Html.ValidationSummary(true)
        <table>
        <tr class="crud_row">
            <td class="number">@Html.LabelFor(model => model.Name)
            </td>
            <td>
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </td>
        </tr>
        <tr class="crud_row">
            <td class="number">@Html.LabelFor(model => model.Email)
            </td>
            <td>
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </td>
        </tr>
        <tr class="crud_row">
            <td class="number">@Html.LabelFor(model => model.Gender)
            </td>
            <td id="genderSelect">
                @{List<Gender> genders = new List<Gender>();
                  foreach(Gender g in Enum.GetValues(typeof(TeamOPSchoolCup.Domain.DTO.Gender)))
                  { 
                      if(!g.Equals(Gender.UNISEX)){
                      genders.Add(g);}
                  }}
                @Html.DropDownListFor(model => model.Gender, new SelectList(genders))
                @Html.ValidationMessageFor(model => model.Gender)
            </td>
        </tr>
        <tr>
            <td>
                <a class="return" href="@Url.Action("Index", "NSSF")">
                    <img src="@Url.Content("~/Content/Images/return_button.png")", alt="Back" />
                    <span>Back</span> </a>
            </td>
            <td class="crud_submit">
                <input id="derp" type="submit" value="Create" />
            </td>
        </tr>
        </table>
    }
</div>

TeamOPSchoolCupWeb/TeamOPSchoolCup.Web/Views/Member/Preferences.cshtml
@using TeamOPSchoolCup.Domain.Resources

@{
    ViewBag.Title = "Preferences";
}

@section schoolCupNav{
    <link rel="Stylesheet" href="@Url.Content("~/Content/css/SchoolCupNavigation.css")" type="text/css" />
    <link rel="Stylesheet" href="@Url.Content("~/Content/css/Profile.css")" type="text/css" />
}

@Html.Partial("_NavigationDetails")

<h1 class="wrappertitel">@PreferencesString.pref</h1>

<div id="cpModel">
@using (Html.BeginForm()) {
    <div>
        <fieldset>
            <legend>@PreferencesString.ChangePreferences</legend>

            <label>@PreferencesString.SelectYourLanguage</label>
            <div class="editor-label">
                @Html.DropDownList("languages")
            </div>
            <p><input type="submit" value="@PreferencesString.Save" /></p>
        </fieldset>
    </div>
}
</div>

TeamOPSchoolCupWeb/TeamOPSchoolCup.Web/Views/Member/Results.cshtml
@model IEnumerable<TeamOPSchoolCup.Domain.POCO.TeamMembership>    
@{
    ViewBag.Title = "Results";
}

@section profile{
    <link rel="Stylesheet" href="@Url.Content("~/Content/css/Profile.css")" type="text/css" />
}
<h1 class="wrappertitel">@TeamOPSchoolCup.Domain.Resources.MemberString.results @ViewBag.memberName</h2>

<p class="profileMenu">@Html.ActionLink(TeamOPSchoolCup.Domain.Resources.MemberString.prof, "Profile", "Member", new { id = ViewBag.memberId }, null) - @Html.ActionLink(TeamOPSchoolCup.Domain.Resources.MemberString.results, "Results", "Member", new { id = ViewBag.memberId }, htmlAttributes: new { @class = "active" })</p>


@foreach(TeamOPSchoolCup.Domain.POCO.TeamMembership mship in Model)
{
   
    if(mship.Results.Count() > 0)
    { 
    <h3 class="center">@Html.ActionLink(mship.Team.Name, "Profile", "Team", new { id = mship.Team.TeamId }, null)</h3>
        <table class="center">
            <tr class="header">
                <th class="meeting">@TeamOPSchoolCup.Domain.Resources.MemberString.meeting</th>
                <th class="event">@TeamOPSchoolCup.Domain.Resources.MemberString.ev</th>
                <th class="result">@TeamOPSchoolCup.Domain.Resources.MemberString.result</th>
            </tr>
            @foreach (TeamOPSchoolCup.Domain.POCO.Result r in mship.Results)
            {
                <tr>
                    <td>@Html.ActionLink(r.Meeting.Name, "Detail", "Meeting", new { id = r.MeetingId }, null)</td>
                    <td>@r.Event.Name</td>
                    <td>@r.ResultScore</td>
                </tr>
            }
        </table>
    } else {
        <p class="center">@TeamOPSchoolCup.Domain.Resources.MemberString.noresults</p>
    }
}  

<div id="graph"></div>

TeamOPSchoolCupWeb/TeamOPSchoolCup.Web/Views/Member/addStudent.cshtml
@model TeamOPSchoolCup.Domain.DTO.BasicMemberInfo
@using TeamOPSchoolCup.Domain.DTO
@using TeamOPSchoolCup.Domain.Resources
@{
    ViewBag.Title = @MemberString.AddStudent;
}
<h1 class="titel">@ViewBag.Title</h1>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<div class="content-form">
@using (Html.BeginForm("AddStudent", "Member", new { teamId = ViewBag.Team.TeamId }, FormMethod.Post))
{
    @Html.ValidationSummary(true)
    <table>
        <tr class="crud_row">
            <td class="number">@Html.LabelFor(Model => Model.Name)</td>
            <td>@Html.EditorFor(Model => Model.Name)@Html.ValidationMessageFor(Model => Model.Name)</td>
        </tr>
        <tr class="crud_row">
            <td class="number">@Html.LabelFor(Model => Model.Email)</td>
            <td>@Html.EditorFor(Model => Model.Email)@Html.ValidationMessageFor(Model => Model.Email)</td>
        </tr>
        <tr class="crud_row">
            <td class="number">@Html.LabelFor(Model => Model.BirthDay)</td>
            <td>@Html.EditorFor(Model => Model.BirthDay, new { DateDropType = TeamOPSchoolCup.Domain.DTO.DateType.STUDENTBIRTHDAY })@Html.ValidationMessageFor(Model => Model.BirthDay)</td>
        </tr>
        <tr class="crud_row">
            <td class="number">@Html.LabelFor(Model => Model.Gender)</td>
            <td id="genderSelect">
                @{List<Gender> genders = new List<Gender>();
                  foreach(Gender g in Enum.GetValues(typeof(TeamOPSchoolCup.Domain.DTO.Gender)))
                  { 
                      if(!g.Equals(Gender.UNISEX)){
                      genders.Add(g);}
                  }}
                @Html.DropDownListFor(model => model.Gender, new SelectList(genders))
                @Html.ValidationMessageFor(model => model.Gender)
            </td>
         </tr>
        <tr>
            <td>
                <a class="return" href="@Url.Action("AddTeamMembership", "Team", new { Id = ViewBag.Team.TeamId })">
                    <img src="@Url.Content("~/Content/Images/return_button.png")", alt="Edit" />
                    <span>Back</span>
                </a>
            </td>
            <td class="crud_submit"><input type="submit" value="Create" /></td>
        </tr>
    </table>
}
</div>