TeamOPSchoolCupWeb/TeamOPSchoolCup.Web/Controllers/AdvertisementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TeamOPSchoolCup.Domain.Services;
using TeamOPSchoolCup.Domain.POCO;
using TeamOPSchoolCup.Domain.DTO;
using System.Web.Script.Serialization;
using System.IO;
using TeamOPSchoolCup.Web.Helpers;
using System.Web.Security;
using TeamOPSchoolCup.Domain.Resources;
using TeamOPSchoolCup.Domain.Exceptions;

namespace TeamOPSchoolCup.Web.Controllers
{
  public class AdvertisementController : Controller
  {
    //
    // GET: /Advertisement/
    [Authorize(Roles="ISFAdmin")]
    public ActionResult Index()
    {
      List<Advertisement> ads = AdvertisementService.GetAdvertisements();
      return View(ads);
    }

    [Authorize(Roles = "ISFAdmin")]
    public ActionResult Details(int id)
    {
      Advertisement ad = AdvertisementService.GetAd(id);
      decimal clicks=ad.AdvertisementStatistics.Sum(x => x.ClickCount);
      decimal views = ad.AdvertisementStatistics.Sum(x => x.ViewCount);
      decimal ctr = (views == 0 ? 0 : ((clicks / views) * 100));
      ViewBag.Statistics=new AdCtr  { Ctr=ctr, Clicks=clicks, Views=views };
     /* ViewBag.Statistics=new { ctr=ctr, clicks=clicks, views=views };
      ViewBag.StatCtr = ctr;
      ViewBag.StatClicks = clicks;
      ViewBag.*/
      return View(AdvertisementService.GetAd(id));
    }

    public ActionResult FooterAd()
    {
      Member member = MemberService.GetMember(email:User.Identity.Name);
      Team team = null;
      var rd = ControllerContext.ParentActionViewContext.RouteData;
      var currentAction = rd.GetRequiredString("action");
      var currentController = rd.GetRequiredString("controller");
      if (currentController.ToLowerInvariant().Equals("team") && currentAction.ToLowerInvariant().Equals("profile")) {
        team = TeamService.GetTeam(Int32.Parse(rd.Values["id"].ToString()));
      }
      AdViewing ad = AdvertisementService.GetApplicableAdvertisement(member:member, team: team);
      if (ad == null) return null;
      return PartialView("FooterAd",ad);
    }

    public ActionResult AdRedirect(int adId, int regionId, int genderValue, int sportId)
    {
      Advertisement ad = AdvertisementService.GetAd(adId);
      Gender? gender = null;
      if (genderValue!=0) gender = (Gender)genderValue;
      AdvertisementService.RegisterClick(ad, regionId, gender, sportId);
      return new RedirectResult(ad.Url);
    }

    [Authorize(Roles = "ISFAdmin")]
    public ActionResult Create()
    {
      //ViewBag.Parent = (parentId.HasValue ? RegionService.GetRegion(parentId.Value) : null);
      if (Roles.IsUserInRole(User.Identity.Name, "Inactive")) { throw new TeamOPSchoolCupException(ErrorStrings.NoPermissionInactive); }
      Region world = RegionService.GetFullTree();
      ViewBag.RegionsJson=new JavaScriptSerializer().Serialize(new RegionForJson(world));
      List<Sport> sports = SportService.GetSports(false).ToList();
      List<object> sportObj = new List<object>();
      foreach (Sport sport in sports)
      {
        sportObj.Add(new { Id = sport.SportId, Name = sport.Name });
      }
      ViewBag.SportsJson = new JavaScriptSerializer().Serialize(sportObj);
      return View();
    }

    //
    // POST: /Region/Create

    [HttpPost]
    [Authorize(Roles = "ISFAdmin")]
    public ActionResult Create(EditableAdvertisement edAdvertisement)
    {
      //Advertisement realAd = edAdvertisement.GetFilledBase();
      if (Roles.IsUserInRole(User.Identity.Name, "Inactive")) { throw new TeamOPSchoolCupException(ErrorStrings.NoPermissionInactive); }
      if (ModelState.IsValid && edAdvertisement.File != null && edAdvertisement.File.ContentLength > 0 /*&& edAdvertisement.File.ContentType != "application/vnd.ms-excel"*/)
      {
        if (AdvertisementService.AddAdvertisementFromEditableAd(edAdvertisement))
        {
          new ImageHelper().Save(new System.Drawing.Bitmap(edAdvertisement.File.InputStream), 728, 90, 100, Path.Combine(Server.MapPath("~/Upload/Advertisement"), "" + edAdvertisement.AdvertisementId + ".jpeg"));
          //string path = Path.Combine(Server.MapPath("~/Upload/Advertisement"), edAdvertisement.File.FileName);
          //edAdvertisement.File.SaveAs(path);
        }
        return RedirectToAction("Details", new { id=edAdvertisement.AdvertisementId });
      }
      if (edAdvertisement.File == null || edAdvertisement.File.ContentLength == 0) { ModelState.AddModelError("", AdvertisementStrings.ModelErrorFileInvalid); }
      //ViewBag.ParentId = new SelectList(RegionService.GetAllRegions(), "RegionId", "Name", region.ParentId);
      Region world = RegionService.GetFullTree();
      ViewBag.RegionsJson = new JavaScriptSerializer().Serialize(new RegionForJson(world));
      List<Sport> sports = SportService.GetSports(false).ToList();
      List<object> sportObj = new List<object>();
      foreach (Sport sport in sports)
      {
        sportObj.Add(new { Id = sport.SportId, Name = sport.Name });
      }
      ViewBag.SportsJson = new JavaScriptSerializer().Serialize(sportObj);
      return View(edAdvertisement);
    }

    [Authorize(Roles = "ISFAdmin")]
    public ActionResult Edit(int id)
    {
      if (Roles.IsUserInRole(User.Identity.Name, "Inactive")) { throw new TeamOPSchoolCupException(ErrorStrings.NoPermissionInactive); }
      Advertisement advertisement = AdvertisementService.GetAd(id);
      EditableAdvertisement edAd = new EditableAdvertisement(advertisement);
      Region world = RegionService.GetFullTree();
      ViewBag.RegionsJson = new JavaScriptSerializer().Serialize(new RegionForJson(world));
      List<Sport> sports = SportService.GetSports(false).ToList();
      List<object> sportObj = new List<object>();
      foreach (Sport sport in sports)
      {
        sportObj.Add(new { Id = sport.SportId, Name = sport.Name });
      }
      ViewBag.SportsJson = new JavaScriptSerializer().Serialize(sportObj);
      //Could use the strings in edAd here...
      //ViewBag.SelectedRegions = new JavaScriptSerializer().Serialize(advertisement.Regions.Select(x => x.RegionId).ToList());
     // ViewBag.SelectedSports = new JavaScriptSerializer().Serialize(advertisement.Sports.Select(x => x.SportId).ToList());
      return View(edAd);
    }

    //
    // POST: /Test/Edit/5

    [HttpPost]
    [Authorize(Roles = "ISFAdmin")]
    public ActionResult Edit(EditableAdvertisement edAd)
    {
      if (Roles.IsUserInRole(User.Identity.Name, "Inactive")) { throw new TeamOPSchoolCupException(ErrorStrings.NoPermissionInactive); }
      //Advertisement realAd = edAdvertisement.GetFilledBase();
      if (ModelState.IsValid)
      {
        if (AdvertisementService.EditAdvertisementFromEditableAd(edAd) && edAd.File != null && edAd.File.ContentLength > 0)
        {
          new ImageHelper().Save(new System.Drawing.Bitmap(edAd.File.InputStream), 728, 90, 100, Path.Combine(Server.MapPath("~/Upload/Advertisement"), "" + edAd.AdvertisementId + ".jpeg"));
        }
        return RedirectToAction("Details", new { id = edAd.AdvertisementId });
      }
      //ViewBag.ParentId = new SelectList(RegionService.GetAllRegions(), "RegionId", "Name", region.ParentId);
      Region world = RegionService.GetFullTree();
      ViewBag.RegionsJson = new JavaScriptSerializer().Serialize(new RegionForJson(world));
      List<Sport> sports = SportService.GetSports(false).ToList();
      List<object> sportObj = new List<object>();
      foreach (Sport sport in sports)
      {
        sportObj.Add(new { Id = sport.SportId, Name = sport.Name });
      }
      ViewBag.SportsJson = new JavaScriptSerializer().Serialize(sportObj);
      //Could use the strings in edAd here...
     // ViewBag.SelectedRegions = new JavaScriptSerializer().Serialize(advertisement.Regions.Select(x => x.RegionId).ToList());
      //ViewBag.SelectedSports = new JavaScriptSerializer().Serialize(advertisement.Sports.Select(x => x.SportId).ToList());
      return View(edAd);
    }
  }
}

TeamOPSchoolCupWeb/TeamOPSchoolCup.Web/Views/Advertisement/Create.cshtml
@model TeamOPSchoolCup.Domain.DTO.EditableAdvertisement
@using TeamOPSchoolCup.Domain.Resources
@{
    ViewBag.Title = AdvertisementStrings.Create;
}
@section advertisement{
    <link rel="Stylesheet" href="@Url.Content("~/Content/css/Vervanging.css")" type="text/css" />
    <link rel="Stylesheet" href="@Url.Content("~/Content/css/dynatree.css")" type="text/css" />
    <script src="@Url.Content("~/Scripts/dynatree.js")"></script>
    <script>
        var regions=@Html.Raw(ViewBag.RegionsJson);
        regions=regions.Children;
        var sports=@Html.Raw(ViewBag.SportsJson);
        var selectedRegions="@(Model == null ? "" : Model.RegionsStr)";
        var selectedSports="@(Model == null ? "" : Model.SportsStr)";
    </script>
    <script src="@Url.Content("~/Scripts/advertisement.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
}
<h1 class="titel">@ViewBag.Title</h1>
<div class="content-form hasDynatree">
@using (Html.BeginForm("Create", "Advertisement", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)
    <table>
        <tr class="crud_row">
            <td class="number">@Html.LabelFor(model => model.Company)</td>
            <td>
                @Html.EditorFor(model => model.Company)
                @Html.ValidationMessageFor(model => model.Company)
            </td>
        </tr>
        <tr class="crud_row">
            <td class="number">@Html.LabelFor(model => model.Begin)</td>
            <td>
                @Html.EditorFor(model => model.Begin, new { DateDropType = TeamOPSchoolCup.Domain.DTO.DateType.FUTURE })
                @Html.ValidationMessageFor(model => model.Begin)
            </td>
        </tr>
        <tr class="crud_row">
            <td class="number">@Html.LabelFor(model => model.End)</td>
            <td>
                @Html.EditorFor(model => model.End, new { DateDropType = TeamOPSchoolCup.Domain.DTO.DateType.FUTURE })
                @Html.ValidationMessageFor(model => model.End)
            </td>
        </tr>
        <tr class="crud_row">
            <td class="number">@Html.LabelFor(model => model.Url)</td>
            <td>
                @Html.EditorFor(model => model.Url)
                @Html.ValidationMessageFor(model => model.Url)
            </td>
        </tr>
        <tr class="crud_row">
            <td class="number">@AdvertisementStrings.ModelGender</td>
            <td>
                <p>@Html.EditorFor(model => model.ForGenderMale) @AdvertisementStrings.Male
                @Html.ValidationMessageFor(model => model.Url)</p>
                <p>@Html.EditorFor(model => model.ForGenderFemale) @AdvertisementStrings.Female
                @Html.ValidationMessageFor(model => model.ForGenderFemale)</p>
            </td>
        </tr>
        <tr class="crud_row">
            <td class="number">@AdvertisementStrings.ModelRegions</td>
            <td>
                <p><a href="#" id="regionsSelectAll">@AdvertisementStrings.SelectAll</a> - <a href="#" id="regionsSelectNone">@AdvertisementStrings.SelectNone</a></p>
                @Html.HiddenFor(model => model.RegionsStr, new { id = "hiddenregions" })
                <ul id="regionselect"></ul>
            </td>
        </tr>
        <tr class="crud_row">
            <td class="number">@AdvertisementStrings.ModelSports</td>
            <td>
                <p><a href="#" id="sportsSelectAll">@AdvertisementStrings.SelectAll</a> - <a href="#" id="sportsSelectNone">@AdvertisementStrings.SelectNone</a></p>
                @Html.HiddenFor(model => model.SportsStr, new { id = "hiddensports" })
                <ul id="sportselect"></ul>
            </td>
        </tr>
        <tr class="crud_row">
            <td class="number">@AdvertisementStrings.Image</td>
            <td>
                <input id="chooseImage" type="file"  accept=".png, .jpg, .jpeg, .gif"  name="File" />
            </td>
        </tr>
        <tr>
            <td>
                <a class="return" href="@Url.Action("Index")">
                    <img src="@Url.Content("~/Content/Images/return_button.png")", alt="Edit" />
                    <span>@AdvertisementStrings.Back</span>
                </a>
            </td>
            <td class="crud_submit"><input type="submit" value="@AdvertisementStrings.Create" /></td>
        </tr>
    </table>
}
</div>

TeamOPSchoolCupWeb/TeamOPSchoolCup.Web/Views/Advertisement/Details.cshtml
@model TeamOPSchoolCup.Domain.POCO.Advertisement
@using TeamOPSchoolCup.Domain.Resources
@using TeamOPSchoolCup.Domain.DTO
@using TeamOPSchoolCup.Domain.Services
@using TeamOPSchoolCup.Domain.POCO
@{
    ViewBag.Title = AdvertisementStrings.Details;
}
@section region{
    <link rel="Stylesheet" href="@Url.Content("~/Content/css/Vervanging.css")" type="text/css" />
}
<div id="detailsScreen">
    <div id="adInfo">
        <p class="title">@AdvertisementStrings.Info</p>
        <div class="adDetailsBox">
            <p><span class="infoTitle">@AdvertisementStrings.ModelCompany:</span> @Model.Company</p>
            <p><span class="infoTitle">@AdvertisementStrings.From</span> @Model.Begin.ToString("dd MMM yyyy") <span class="infoTitle">@AdvertisementStrings.until</span> @Model.End.ToString("dd MMM yyyy")</p>
            <p><span class="infoTitle">@AdvertisementStrings.ModelUrl:</span> @Model.Url</p>
            <p class="genderline">
                <span class="infoTitle">@AdvertisementStrings.ModelGender:</span> 
                @if (Model.ForGenderMale) { <img class='gender' id='male' src='@Url.Content("~/Content/images/man.png")' alt='gender'/> }
                @if (Model.ForGenderFemale) { <img class='gender' id='female' src='@Url.Content("~/Content/images/woman.png")' alt='gender'/> }
            </p>
            <p id="edit"><a href="@Url.Action("Edit","Advertisement", new { id = Model.AdvertisementId })"><img alt="edit" title="Edit" src="@Url.Content("~/Content/images/gear.png")"/><span>Edit</span></a></p>
        </div>
    </div>
    <div id="clickThrough">
        <p class="title">@AdvertisementStrings.ClickThroughRate</p>
        <div class="adDetailsBox">
            <span id="ctr">@Math.Round(ViewBag.Statistics.Ctr, 2)%</span>
            <p>@ViewBag.Statistics.Clicks <span class="infoTitle">@AdvertisementStrings.Clicks</span>, @ViewBag.Statistics.Views <span class="infoTitle">@AdvertisementStrings.Views</span></p>
        </div>
    </div>
    <div class="clearfix"></div>
    <div id="statistics">
        <p class="title">@AdvertisementStrings.Statistics</p>
        <div class="adDetailsBox">
            <table id="rankingTable alternatingRows"> 
                <tr class="tableHeader header">
                    <th id="first">@AdvertisementStrings.Region</th>
                    <th>@AdvertisementStrings.ModelGender</th>
                    <th>@AdvertisementStrings.Sport</th>
                    <th>@AdvertisementStrings.Views</th>
                    <th>@AdvertisementStrings.Clicks</th>
                </tr>           
                @foreach (var stat in Model.AdvertisementStatistics)
                {
                    <tr>
                        <td>@stat.Region.Name</td>
                        <td class="centeredcell">
                            @if (!stat.Gender.HasValue) { <img class='gender' id='unknown-gender' src='@Url.Content("~/Content/images/questionmark.png")' alt='@AdvertisementStrings.Unknown' /> }
                            @if (stat.Gender.HasValue && stat.Gender == Gender.MALE) { <img class='gender' id='male' src='@Url.Content("~/Content/images/man.png")' alt='@AdvertisementStrings.Male'/> }
                            @if (stat.Gender.HasValue && stat.Gender == Gender.FEMALE) { <img class='gender' id='female' src='@Url.Content("~/Content/images/woman.png")' alt='@AdvertisementStrings.Female'/> }
                        </td>
                        <td class="centeredcell">
                            @if (stat.SportId == 0) { <img class='sport-image' id='unknown-sport' src='@Url.Content("~/Content/images/questionmark.png")' alt='@AdvertisementStrings.Unknown' /> }
                            @if (stat.SportId != 0) { Sport sport=SportService.GetSport(stat.SportId); <img class="sport-image" id="sport-@sport.Name" src="@Url.Content("~/Content/images/" + sport.Name + ".png")" alt="@sport.Name" /> }
                        </td>
                        <td class="centeredcell">@stat.ViewCount</td>
                        <td class="centeredcell">@stat.ClickCount</td>
                    </tr>
                } 
            </table>
        </div>
    </div>
</div>

TeamOPSchoolCupWeb/TeamOPSchoolCup.Web/Views/Advertisement/Edit.cshtml
@model TeamOPSchoolCup.Domain.DTO.EditableAdvertisement
@using TeamOPSchoolCup.Domain.Resources
@{
    ViewBag.Title = @AdvertisementStrings.Edit;
}
@section advertisement{
    <link rel="Stylesheet" href="@Url.Content("~/Content/css/Vervanging.css")" type="text/css" />
    <link rel="Stylesheet" href="@Url.Content("~/Content/css/dynatree.css")" type="text/css" />
    <script src="@Url.Content("~/Scripts/dynatree.js")"></script>
    <script>
        var regions=@Html.Raw(ViewBag.RegionsJson);
        regions=regions.Children;
        var sports=@Html.Raw(ViewBag.SportsJson);
        var selectedRegions="@Model.RegionsStr";
        var selectedSports="@Model.SportsStr";
    </script>
    <script src="@Url.Content("~/Scripts/advertisement.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
}
<h1 class="titel">@ViewBag.Title</h1>
<div class="content-form advertisementEdit hasDynatree">
@using (Html.BeginForm("Edit", "Advertisement", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.AdvertisementId)
    <table>
        <tr class="crud_row">
            <td class="number">@Html.LabelFor(model => model.Company)</td>
            <td>
                @Html.EditorFor(model => model.Company)
                @Html.ValidationMessageFor(model => model.Company)
            </td>
        </tr>
        <tr class="crud_row">
            <td class="number">@Html.LabelFor(model => model.Begin)</td>
            <td>
                @Html.EditorFor(model => model.Begin, new { DateDropType = TeamOPSchoolCup.Domain.DTO.DateType.FUTURE })
                @Html.ValidationMessageFor(model => model.Begin)
            </td>
        </tr>
        <tr class="crud_row">
            <td class="number">@Html.LabelFor(model => model.End)</td>
            <td>
                @Html.EditorFor(model => model.End, new { DateDropType = TeamOPSchoolCup.Domain.DTO.DateType.FUTURE })
                @Html.ValidationMessageFor(model => model.End)
            </td>
        </tr>
        <tr class="crud_row">
            <td class="number">@Html.LabelFor(model => model.Url)</td>
            <td>
                @Html.EditorFor(model => model.Url)
                @Html.ValidationMessageFor(model => model.Url)
            </td>
        </tr>
        <tr class="crud_row">
            <td class="number">@AdvertisementStrings.ModelGender</td>
            <td>
                <p>@Html.EditorFor(model => model.ForGenderMale) @AdvertisementStrings.Male
                @Html.ValidationMessageFor(model => model.Url)</p>
                <p>@Html.EditorFor(model => model.ForGenderFemale) @AdvertisementStrings.Female
                @Html.ValidationMessageFor(model => model.ForGenderFemale)</p>
            </td>
        </tr>
        <tr class="crud_row">
            <td class="number">@AdvertisementStrings.ModelRegions</td>
            <td>
                <p><a href="#" id="regionsSelectAll">@AdvertisementStrings.SelectAll</a> - <a href="#" id="regionsSelectNone">@AdvertisementStrings.SelectNone</a></p>
                @Html.HiddenFor(model => model.RegionsStr, new { id = "hiddenregions" })
                <ul id="regionselect"></ul>
            </td>
        </tr>
        <tr class="crud_row">
            <td class="number">@AdvertisementStrings.ModelSports</td>
            <td>
                <p><a href="#" id="sportsSelectAll">@AdvertisementStrings.SelectAll</a> - <a href="#" id="sportsSelectNone">@AdvertisementStrings.SelectNone</a></p>
                @Html.HiddenFor(model => model.SportsStr, new { id = "hiddensports" })
                <ul id="sportselect"></ul>
            </td>
        </tr>
        <tr class="crud_row">
            <td class="number">@AdvertisementStrings.Image</td>
            <td>
                <img src="@Url.Content("~/Upload/Advertisement/"+Model.AdvertisementId+".jpeg")" alt="@Model.Company" />
                <input type="file"  accept=".png, .jpg, .jpeg, .gif"  name="File" />
            </td>
        </tr>
        <tr>
            <td>
                <a class="return" href="@Url.Action("Index")">
                    <img src="@Url.Content("~/Content/Images/return_button.png")", alt="Edit" />
                    <span>@AdvertisementStrings.Back</span>
                </a>
            </td>
            <td class="crud_submit"><input type="submit" value="@AdvertisementStrings.Save" /></td>
        </tr>
    </table>
}
</div>

TeamOPSchoolCupWeb/TeamOPSchoolCup.Web/Views/Advertisement/FooterAd.cshtml
 @model TeamOPSchoolCup.Domain.DTO.AdViewing
 @using TeamOPSchoolCup.Web.Helpers
 <div id="footerad"> @Html.ActionImage("AdRedirect","Advertisement",new { adId = Model.Advertisement.AdvertisementId, regionId=Model.RegionId,genderValue=(Model.Gender == null ? 0 : (int)Model.Gender), sportId=Model.SportId },"~/Upload/Advertisement/"+Model.Advertisement.AdvertisementId+".jpeg",Model.Advertisement.Company)</div>

TeamOPSchoolCupWeb/TeamOPSchoolCup.Web/Views/Advertisement/Index.cshtml
@model IEnumerable<TeamOPSchoolCup.Domain.POCO.Advertisement>
@using TeamOPSchoolCup.Web.Helpers
@using TeamOPSchoolCup.Domain.Resources
@{
    ViewBag.Title = AdvertisementStrings.Index;
}
@section advertisement{
    <link rel="Stylesheet" href="@Url.Content("~/Content/css/Vervanging.css")" type="text/css" />
}
<h1 class="wrappertitel">@AdvertisementStrings.Advertisements</h1>
<div id="add"><div id="add1"><a href="@Url.Action("Create", "Advertisement")">@AdvertisementStrings.CreateOne</a></div></div>
<table class="alternatingRows">
    <tr class="header">
        <th class="head" id="numberHeader" />
        <th class="head companynamecell">@AdvertisementStrings.ModelCompany</th>
        <th class="head">@AdvertisementStrings.ModelBegin</th>
        <th class="head">@AdvertisementStrings.ModelEnd</th>
        <th class="head">@AdvertisementStrings.ModelUrl</th>
        <th class="head"/>
    </tr>
    @{int index = 1;}
    @foreach (var ad in Model)
    {
    <tr>
        <td class="number">@index</td>
        <td class="infocell companynamecell">@Html.ActionLink(ad.Company, "Details", new { id = ad.AdvertisementId })</td>
        <td class="infocell">@ad.Begin.ToString("dd MMM yyyy")</td>
        <td class="infocell">@ad.End.ToString("dd MMM yyyy")</td>
        <td class="infocell"><a target="_blank" href="@ad.Url.">@ad.Url</a></td>
        <td class="last"><a href="@Url.Action("Edit","Advertisement", new { id = ad.AdvertisementId })"><img alt="edit" title="Edit" src="@Url.Content("~/Content/images/gear.png")"/></a></td>
    </tr>
    index += 1;
    }  
</table>