TeamOPSchoolCupWeb/TeamOPSchoolCup.Web/Controllers/RankingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TeamOPSchoolCup.Domain.POCO;
using TeamOPSchoolCup.Domain.POCO.Ranking;
using TeamOPSchoolCup.Domain.DAL;
using TeamOPSchoolCup.Domain.Services;
using TeamOPSchoolCup.Domain.DTO;
using TeamOPSchoolCup.Web.Helpers;


namespace TeamOPSchoolCup.Web.Controllers
{
  public class RankingController : Controller
  {
    //
    // GET: /Ranking/

    public ActionResult Index()
    {
      return View();
    }

    public ActionResult LoadStudentRankings(int? pEventId, int? year, int? regionId,
        Gender? gender, 
        ParticipantAge? age,
        int? page, int? pageSize)
    {
        int pageSizeValue = pageSize.HasValue ? pageSize.Value : 50; // CHANGE THIS LINE IF YOU LOVE LOGIC
        // Parameters
        int eventValue = pEventId.HasValue ? pEventId.Value : 1;
        int regionValue = regionId.HasValue ? regionId.Value : 5;

        Region region = RegionService.GetRegion(regionValue);
        List<BestStudentResult> bsr = RankingService.GetStudentRanking(pEvent: EventService.GetEvent(eventValue),
        year: year, isOfficial: true, gender: gender, participantAge: age, regions: new List<Region> { region });

        var paginatedBSR = new PaginatedList<BestStudentResult>(bsr.ToList(), page ?? 0, pageSizeValue);

        return PartialView("Partials/_StudentRankingTable", paginatedBSR);
    }

    public ActionResult LoadTeamRankings(int? sportId, int? year, int? regionId, Gender? gender, int? page, int? pageSize)
    {
        // number of elements per page
        int pageSizeValue = pageSize.HasValue ? pageSize.Value : 10; // CHANGE THIS LINE IF YOU LOVE LOGIC
        // Parameters
        int sportValue = sportId.HasValue ? sportId.Value : 1;
        int regionValue = regionId.HasValue ? regionId.Value : 1;
        Region region = RegionService.GetRegion(regionValue);
        // Get BTR
        List<BestTeamResult> btr = RankingService.GetTeamRanking(sport: SportService.GetSport(sportValue), gender: gender, year: year,regions: new List<Region> { region });

        // Get Paginated list
        var paginatedBTR = new PaginatedList<BestTeamResult>(btr.ToList(), page ?? 0, pageSizeValue);

        return PartialView("Partials/_TeamRankingTable", paginatedBTR);
    }

    public ActionResult LoadEventsFromSport(int? id) 
    {
        int sportValue = id.HasValue ? id.Value : 1;
        

        ViewBag.events = new SelectList(EventService.GetEventsOfSport(sportValue), "EventId", "Name");
        return PartialView("Partials/_SportEvents");
    }

    public ActionResult Team()
    {
        // Get world subregions
        ViewBag.team_regions = RegionService.GetAllRegions();

        ViewBag.team_sports = new SelectList(SportService.GetSports(true), "SportId", "Name");
        ViewBag.team_events = new SelectList(EventService.GetEventsOfSport(SportService.GetSport(abbr:"ATH").SportId), "EventId", "Name");

       
        return View("Team");
    }

    public ActionResult Student()
    {
        ViewBag.student_regions = RegionService.GetAllRegions();
        ViewBag.student_sports = new SelectList(SportService.GetSports(true), "SportId", "Name");
        ViewBag.student_events = new SelectList(EventService.GetEventsOfSport(SportService.GetSport(abbr:"ATH").SportId), "EventId", "Name");
        return View("Student");
    }


    public ActionResult StudentPartial() {
        ViewBag.student_regions = RegionService.GetAllRegions();

        ViewBag.student_sports = new SelectList(SportService.GetSports(true), "SportId", "Name");
        ViewBag.student_events = new SelectList(EventService.GetEventsOfSport(SportService.GetSport(abbr:"ATH").SportId), "EventId", "Name");
        // Gender values
        var genders = from Gender e in Enum.GetValues(typeof(Gender))
                      select new { Id = e, Name = e };
        genders = genders.Where(x => x.Name != Gender.UNISEX);

        ViewBag.student_genders = new SelectList(genders, "Id", "Name");
        ViewBag.student_years = new SelectList(CompetitionYearService.GetCompetitionYears(), "CompetitionYearValue", "CompetitionYearValue");

        var ages = from ParticipantAge e in Enum.GetValues(typeof(ParticipantAge))
                   select new { Id = (int)e, Name = (int)e };
        ViewBag.student_ages = new SelectList(ages, "Id", "Name");

        return PartialView("Partials/_Student");
    }

    public ActionResult TeamPartial()
    {
        // Get world subregions
        ViewBag.team_regions = RegionService.GetAllRegions();
        ViewBag.team_sports = new SelectList(SportService.GetSports(true), "SportId", "Name");
        ViewBag.team_years = new SelectList(CompetitionYearService.GetCompetitionYears(), "CompetitionYearValue", "CompetitionYearValue");
        var genders = from Gender e in Enum.GetValues(typeof(Gender))
                      select new { Id = e, Name = e };
        genders = genders.Where(x => x.Name != Gender.UNISEX);

        ViewBag.team_genders = new SelectList(genders, "Id", "Name");

        return PartialView("Partials/_Team");
    }


  }
}

TeamOPSchoolCupWeb/TeamOPSchoolCup.Web/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TeamOPSchoolCup.Domain.Services;
using TeamOPSchoolCup.Domain.POCO.Members;

namespace TeamOPSchoolCup.Web.Controllers
{
    public class StudentsController : Controller
    {
        //
        // GET: /Students/

        public ActionResult Index()
        {
            return View(MemberService.GetStudents());
        }

    }
}

TeamOPSchoolCupWeb/TeamOPSchoolCup.Web/Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TeamOPSchoolCup.Domain.POCO;
using TeamOPSchoolCup.Domain.DAL;
using TeamOPSchoolCup.Domain.DTO;
using TeamOPSchoolCup.Domain.POCO.Members;
using TeamOPSchoolCup.Domain.Services;
using TeamOPSchoolCup.Domain.POCO.Ranking;
using System.IO;
using TeamOPSchoolCup.Web.Helpers;
using System.Web.Script.Serialization;
using System.Web.Security;
using TeamOPSchoolCup.Domain.Resources;
using TeamOPSchoolCup.Domain.Exceptions;

namespace TeamOPSchoolCup.Web.Controllers
{
  public class TeamController : Controller
  {

    public ViewResult Profile(int id) {
      Team team = TeamService.GetTeam(id);
      ViewBag.teamRankings = RankingService.GetRankings(team);
      ViewBag.teamMembers = TeamService.GetTeamMemberships(team, null, TeamService.Historicality.CURRENT);
      string photoPath = "~/Upload/Teampicture/"+id+".jpeg";
      string photoPathTest = Server.MapPath("~/Upload/Teampicture/" + id + ".jpeg");
      string logoPath = "~/Upload/Teamlogo/" + id + ".jpeg";
      string logoPathTest = Server.MapPath("~/Upload/Teamlogo/" + id + ".jpeg");      
      ViewBag.photopath = photoPath;
      ViewBag.photopathTest = photoPathTest;
      ViewBag.logopath = logoPath;
      ViewBag.logopathTest = logoPathTest;
      return View(team);

    }
    public ActionResult TeamResults(int teamId)
    {
      int year = DateTime.Today.Year;
      Team team = TeamService.GetTeam(teamId);
      List<Event> events = EventService.GetEvents(teamId: teamId);
      List<Result> results = ResultService.GetResults(team: team);
                
      TeamComparison.StudentsInTeamsWithEvents teamData = new TeamComparison.StudentsInTeamsWithEvents();
      teamData.TeamId = team.TeamId;
      teamData.Name = team.Name;
      foreach (TeamMembership tm1 in TeamService.GetTeamMemberships(team))
      {
        TeamComparison.StudentsParticipatingEvents spe = new TeamComparison.StudentsParticipatingEvents();
        spe.Id = tm1.MemberId;
        spe.Name = tm1.Student.Member.Name;
        events.ForEach(x => spe.ParticipatingEvents.Add(x.Name, EventService.GetEvents(tm1.MemberId).Select(y => y.EventId).Contains(x.EventId)));
        teamData.Students.Add(spe);
      }

     
      List<TeamComparison.StudentsInTeamsWithEvents> data = new List<TeamComparison.StudentsInTeamsWithEvents>();
      data.Add(teamData);
      ViewBag.StudentsInTeamsWithEventsData = data;
      ViewBag.Sports = new SelectList(SportService.GetSports(true), "SportId", "Name");
      ViewBag.Meetings = new SelectList(MeetingService.GetMeetings(team: team), "MeetingId", "Name");
      ViewBag.Events = new SelectList(EventService.GetEventsOfMeeting(MeetingService.GetMeeting(4)), "EventId", "Name");
                
      ViewBag.StudentsInTeamsWithEvents = new JavaScriptSerializer().Serialize(data);
      return View(results);
    }
    public ActionResult LoadTeamResult(int teamId, bool? official, int? sportId, int? meetingId, int? pEventId, int? page, int? pageSize)
    {
      int pageSizeValue = pageSize.HasValue ? pageSize.Value : 5; // CHANGE THIS LINE IF YOU LOVE LOGIC
      // Parameters

      List<Result> mr = ResultService.GetTeamResults(teamId, official, sportId, meetingId, pEventId);

      var paginatedMR = new PaginatedList<Result>(mr.ToList(), page ?? 0, pageSizeValue);

      return PartialView("Partials/_TeamResultsTable", paginatedMR);
    }
    [Authorize(Roles="Student,Coach")]
    public ActionResult Dashboard(int id) {
      Team team = TeamService.GetTeam(id);
      Member m = MemberService.GetMember(email: User.Identity.Name);

      if (m.Coach != null)
      {
        if (!m.Coach.TeamCoaches.Select(x => x.TeamId).Contains(team.TeamId)) throw new TeamOPSchoolCupException(ErrorStrings.Team_Dashboard_CoachNoAccess);
        ViewBag.StudCoach = false;
      }
      else if (m.Student != null)
      {
        if (!m.Student.TeamMemberShips.Select(x => x.TeamId).Contains(team.TeamId)) throw new TeamOPSchoolCupException(ErrorStrings.Team_Dashboard_StudentNoAccess);
        ViewBag.StudCoach = true;
      }

      ViewBag.BestTeamResult = RankingService.GetBestTeamResult(team,DateTime.Today.Year);
      ViewBag.Topics = ConversationService.GetTopicsOfTeam(team, true);
      ViewBag.UserId = m.MemberId;
      ViewBag.TeamRankings = RankingService.GetRankings(team);
      ViewBag.LatestTopicMessage = ConversationService.GetFirstMessage(ConversationService.GetLatestSpotlightTopic(team));
      return View(team);
    }

    public ActionResult Topic(int id) {
      Topic topic = ConversationService.GetTopic(id);
      ViewBag.Topics = ConversationService.GetTopicsOfTeam(topic.Team, true);
      ViewBag.Messages = ConversationService.GetMessagesOfTopic(id);
      ViewBag.Topic = topic;
      Message message = new Message();
      message.TopicId = topic.TopicId;
      return View(message);
    }

    [HttpPost]
    public ActionResult Topic(Message message) {
      if (Roles.IsUserInRole(User.Identity.Name, "Inactive")) { throw new TeamOPSchoolCupException(ErrorStrings.Member_Inactive_NoAccess); }
      if (ModelState.IsValid) {
        if (User.Identity.IsAuthenticated) {
          Member m = MemberService.GetMember(email: User.Identity.Name);
          if (m.Student != null || m.Coach != null) {
            message.DatePosted = DateTime.Now;
            if (m.Student != null && m.Coach == null) {
              ConversationService.AddMessage(message, studentId: m.MemberId, topicId: message.TopicId);
            }
            else {
              ConversationService.AddMessage(message, coachId: m.MemberId, topicId: message.TopicId);
            }
          }
        }
      }
      return RedirectToAction("Topic", new { id = message.TopicId });
    }

    //
    // GET: /Team/Create

    public ActionResult Create() {
      if (Roles.IsUserInRole(User.Identity.Name, "Inactive")) { throw new TeamOPSchoolCupException(ErrorStrings.NoPermissionInactive); }
      ViewBag.SportId = new SelectList(SportService.GetSports(true), "SportId", "Name");
      return View();
    }

    //
    // POST: /Team/Create

    [HttpPost]
    public ActionResult Create(Team team, HttpPostedFileBase Logo, HttpPostedFileBase Photo) {
      if (Roles.IsUserInRole(User.Identity.Name, "Inactive")) { throw new TeamOPSchoolCupException(ErrorStrings.NoPermissionInactive); }
      if (ModelState.IsValid) {
        Coach coach = MemberService.GetCoach(MemberService.GetMember(email: User.Identity.Name).MemberId);
        
        team.SchoolId = coach.SchoolId;

        TeamService.AddTeam(team);

        if (Photo != null && Logo != null
          && Photo.ContentLength > 0 && Logo.ContentLength > 0) {
          new ImageHelper().Save(new System.Drawing.Bitmap(Photo.InputStream), 180, 130, 80, Path.Combine(Server.MapPath("~/Upload/Teampicture"), "" + team.TeamId + ".jpeg"));
          new ImageHelper().Save(new System.Drawing.Bitmap(Logo.InputStream), 100, 100, 80, Path.Combine(Server.MapPath("~/Upload/Teamlogo"), "" + team.TeamId + ".jpeg"));
        }
        if (Photo != null &&Photo.ContentLength > 0
                  && Logo == null) {
          new ImageHelper().Save(new System.Drawing.Bitmap(Photo.InputStream), 180, 130, 80, Path.Combine(Server.MapPath("~/Upload/Teampicture"), "" + team.TeamId + ".jpeg"));
        }
        if (Photo == null
                && Logo != null && Logo.ContentLength > 0) {
          new ImageHelper().Save(new System.Drawing.Bitmap(Logo.InputStream), 180, 130, 80, Path.Combine(Server.MapPath("~/Upload/Teamlogo"), "" + team.TeamId + ".jpeg"));
        }

        if (!MemberService.AddCoachToTeam(coach.MemberId, team.TeamId))
        {
          throw new Exception();
        }
        
      }
     return RedirectToAction("SchoolCup", "SchoolCup");
    }

    [Authorize(Roles="Coach")]
    public ActionResult AddTeamMembership(int id) {
      if (Roles.IsUserInRole(User.Identity.Name, "Inactive")) { throw new TeamOPSchoolCupException(ErrorStrings.AddTeamMembership_NoPermission); }
      Team t = TeamService.GetTeam(id: id);
      if (t.TeamCoaches.Single(tc => tc.DateLeft >= DateTime.Today).MemberId != MemberService.GetMember(email: User.Identity.Name).MemberId) { throw new TeamOPSchoolCupException(ErrorStrings.Result_CantAddResultsToMeeting); /*TODO ERROR*/ }
      List<Student> students = TeamService.GetPotentialTeamMembers(t);
      ViewBag.Team = t;
      return View(students);
    }

    //[HttpPost]
    [Authorize(Roles = "Coach")]
    public ActionResult ActualAddTeamMembership(int teamId, Guid studentId)
    {
      if (Roles.IsUserInRole(User.Identity.Name, "Inactive")) { throw new TeamOPSchoolCupException(ErrorStrings.Result_CantAddResultsToMeeting); }
      if (TeamService.AddTeamMembership(teamId, studentId)) {
        return RedirectToAction("AddTeamMembership", new { id = teamId });
      }
      else { throw new TeamOPSchoolCupException(ErrorStrings.Result_CantAddResultsToMeeting); }
    }

    [Authorize(Roles="Coach")]
    public ActionResult TeamManagement(int id) {
      Team team = TeamService.GetTeam(id);
      if (User.Identity.IsAuthenticated) {
        Member m = MemberService.GetMember(email:User.Identity.Name);
        if (m.Coach != null)
        {
          if (!m.Coach.TeamCoaches.Select(x => x.TeamId).Contains(team.TeamId)) throw new TeamOPSchoolCupException(ErrorStrings.Team_Dashboard_CoachNoAccess);
          ViewBag.StudCoach = false;
        }
        if (m.Student != null || m.Coach != null) {
          if (m.Student != null && m.Coach == null) {
            ViewBag.StudCoach = true;
          }
          else {
            ViewBag.StudCoach = false;
          }
        }
      }
      EditableTeam edTeam = new EditableTeam(team);

      return View(edTeam);
    }

    [HttpPost]
    public ActionResult TeamManagement(EditableTeam eteam) {

TeamOPSchoolCupWeb/TeamOPSchoolCup.Web/Views/Ranking/Partials/_SportEvents.cshtml
@Html.DropDownList("events")

TeamOPSchoolCupWeb/TeamOPSchoolCup.Web/Views/Ranking/Partials/_Student.cshtml
@using TeamOPSchoolCup.Domain.Resources
@using TeamOPSchoolCup.Domain.POCO
@using TeamOPSchoolCup.Domain.Services
<div id="student_rankings">
    <table class="filters">
           <tr>
                <td>@RankingStrings.Sport</td>
                <td>@RankingStrings.Event</td>
                <td>@RankingStrings.Regions</td>
                <td>@RankingStrings.Year</td>
                <td>@RankingStrings.Gender</td>
                <td>@RankingStrings.Age</td>
                @if (User.Identity.IsAuthenticated && User.IsInRole("Student"))
                {
                    <td>@RankingStrings.Me</td>
                }
                <td>@RankingStrings.Compare</td>
           </tr>
           <tr>
                <td class="selectFilter"><label>@Html.DropDownList("student_sports")</label></td>
                <td class="selectFilter"><label>@Html.DropDownList("student_events")</label></td>
                <td class="selectFilter">
                    <label>
                        <select id="student_regions">
                        <option value="1">World </option>  
                            @foreach (TeamOPSchoolCup.Domain.POCO.Region continent in ViewBag.student_regions) {
                                if (continent.ParentId == 1)
                                {
                                    <option value="@Html.DisplayFor(modelitem => continent.RegionId)">@Html.DisplayFor(modelItem => continent.Name)  </option>  
                                    foreach (TeamOPSchoolCup.Domain.POCO.Region country in ViewBag.student_regions)
                                    {

                                        if (country.ParentId == continent.RegionId)
                                        {
                                          <option value="@Html.DisplayFor(modelitem => country.RegionId)">&nbsp; @Html.DisplayFor(modelItem => country.Name)  </option>
                                            foreach (TeamOPSchoolCup.Domain.POCO.Region region in ViewBag.student_regions)
                                            {
                                                if (region.ParentId == country.RegionId)
                                                {
                                                        <option value="@Html.DisplayFor(modelitem => region.RegionId)">&nbsp; &nbsp; &nbsp; @Html.DisplayFor(modelItem => region.Name)  </option>  
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        </select>
                    </label>
                </td>
           <td class="selectFilter"><label>@Html.DropDownList("student_years", String.Empty)</label></td>
           <td class="selectFilter"><label>@Html.DropDownList("student_genders")</label></td>
           <td class="selectFilter"><label>@Html.DropDownList("student_ages", String.Empty)</label></td>
           @if (User.Identity.IsAuthenticated && User.IsInRole("Student"))
           {
                <td class="selectFilter"><input type="checkbox" id="compare_me" value="@MemberService.GetMember(email: User.Identity.Name).MemberId" /></td>
           }
           <td class="selectFilter"><input type="button" id="compare" name="compare" value="Compare"/></td>
           </tr>

    </table>

        @Html.Action("LoadStudentRankings", "Ranking")
    </div>

TeamOPSchoolCupWeb/TeamOPSchoolCup.Web/Views/Ranking/Partials/_StudentRankingTable.cshtml
@model TeamOPSchoolCup.Web.Helpers.PaginatedList<TeamOPSchoolCup.Domain.POCO.Ranking.BestStudentResult>
@using TeamOPSchoolCup.Domain.Resources

<table  id="student_rankingtable" class="pagertable">
@if (Model.TotalCount > 0)
{
    <tr class="header">
        <th id="rank" />
        <th id="name">@RankingStrings.Name</th>
        <th id="meeting">@RankingStrings.Meeting</th>
        <th id="measure">@RankingStrings.Measure</th>
        <th id="points">@RankingStrings.Result</th>
        <th id="compare">@RankingStrings.Compare</th>

    </tr> 
    int index = 1;
    index = (Model.PageIndex * Model.PageSize) + 1;
    foreach (var rank in Model)
    {
        <tr id="row">
            <td class="number">
                @index
            </td>
            <td class="ranking">
                @Html.ActionLink(rank.Student.Member.Name, "Profile", "Member", new { id = rank.Student.MemberId }, htmlAttributes: new { @class = "profile_link" })    
            </td>
            <td class="ranking">
                 @Html.ActionLink(rank.Result.Meeting.Name, "Detail", "Meeting", new { id = rank.Result.MeetingId }, htmlAttributes: new { @class = "profile_link" })   
            </td>
            <td class="ranking">
                @Html.DisplayFor(modelItem => rank.Event.Unit)  
            </td>
            <td class="ranking">
                @Html.DisplayFor(modelItem => rank.Result.ResultScore)    
            </td>
            <td class="compare"><input name="student_compare" value="@Html.DisplayFor(modelitem => rank.MemberId)" type="checkbox" id="student_compare" /></td>
            @{ index += 1; }
        </tr>
    }  
    <tr class="tablebottomactions">
        <td colspan="2">
            @if (Model.PageIndex > 0)
            { 
                <a class="pager" id="previous"><img src="@Url.Content("~/Content/images/return_button.png")" alt="@SharedStrings.Previous" /><span>@SharedStrings.Previous</span></a>
            }
        </td>
        <td></td><td></td>
        <td id="nextparent" colspan="2">
            @if (Model.HasNextPage && Model.PageIndex < Model.TotalPages)
            {
               <a class="pager" id="next"><span>@SharedStrings.Next</span><img src="@Url.Content("~/Content/images/next_button.png")" alt="@SharedStrings.Next" /></a>
            } 
        </td>
        
    </tr>

}
else
{ 
    <tr><td>@RankingStrings.NoRankingsFound</td></tr>
}
</table>

TeamOPSchoolCupWeb/TeamOPSchoolCup.Web/Views/Ranking/Partials/_Team.cshtml
@using TeamOPSchoolCup.Domain.Resources
<div id="team_rankings">
    <table class="filters">
           <tr>
                <td>@RankingStrings.Sport</td>
                <td>@RankingStrings.Regions</td>
                <td>@RankingStrings.Year</td>
                <td>@RankingStrings.Gender</td>
                <td>@RankingStrings.Compare</td>
           </tr>
           <tr>
                <td class="selectFilter"><label>@Html.DropDownList("team_sports")</label></td>
                <td class="selectFilter">
                    <label>
                        <select id="team_regions">
                            <option value="1">World </option>  
                            @foreach (TeamOPSchoolCup.Domain.POCO.Region continent in ViewBag.team_regions)
                            {
                                if (continent.ParentId == 1 )
                                {
                                    <option value="@Html.DisplayFor(modelitem => continent.RegionId)">@Html.DisplayFor(modelItem => continent.Name)  </option>  
                                    foreach (TeamOPSchoolCup.Domain.POCO.Region country in ViewBag.team_regions)
                                    {
                                        if (country.ParentId == continent.RegionId)
                                        {
                                          <option value="@Html.DisplayFor(modelitem => country.RegionId)">&nbsp; @Html.DisplayFor(modelItem => country.Name)  </option>
                                            foreach (TeamOPSchoolCup.Domain.POCO.Region region in ViewBag.team_regions)
                                            {
                                                if (region.ParentId == country.RegionId)
                                                {
                                                        <option value="@Html.DisplayFor(modelitem => region.RegionId)">&nbsp; &nbsp; &nbsp; @Html.DisplayFor(modelItem => region.Name)  </option>  
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        </select>
                    </label>
                </td>
            <td class="selectFilter"><label>@Html.DropDownList("team_years", String.Empty)</label></td>
            <td class="selectFilter"><label>@Html.DropDownList("team_genders")</label></td>
            <td class="selectFilter"><input type="button" id="compareTeam" name="compareTeam" value="Compare"/></td>
           </tr>

    </table>
    @Html.Action("LoadTeamRankings", "Ranking", new { sportId = ((SelectList)ViewBag.team_sports).First().Value })
</div>

TeamOPSchoolCupWeb/TeamOPSchoolCup.Web/Views/Ranking/Partials/_TeamRankingTable.cshtml
@model TeamOPSchoolCup.Web.Helpers.PaginatedList<TeamOPSchoolCup.Domain.POCO.Ranking.BestTeamResult>
@using TeamOPSchoolCup.Domain.Resources
<table id="team_rankingtable" class="pagertable">
@if (Model.TotalCount > 0)
{
    <tr class="header">
        <th id="rank" />
        <th id="name">@RankingStrings.Name</th>
        <th id="school">@RankingStrings.School</th>
        <th id="meeting">@RankingStrings.Meeting</th>
        <th id="points">@RankingStrings.Result</th>
        @if (Model.First().CompetitionYear == DateTime.Today.Year)
        {
            <th id="compare">@RankingStrings.Compare</th>
        }
    </tr>
    int index = 1;
    index = (Model.PageIndex * Model.PageSize) + 1;
    foreach (var rank in Model)
    {
        <tr id="row">
            <td class="number">
                @index
            </td>
            <td class="ranking">
                @Html.ActionLink(rank.TeamResult.Team.Name, "Profile", "Team", new { id = rank.TeamResult.Team.TeamId }, htmlAttributes: new { @class = "profile_link" })    
            </td>
             <td class="ranking">
                @Html.DisplayFor(modelItem => rank.TeamResult.Team.School.Name)    
            </td>
            <td class="ranking">
                @Html.ActionLink(rank.TeamResult.Meeting.Name, "Detail", "Meeting", new { id = rank.TeamResult.MeetingId }, htmlAttributes: new { @class = "profile_link" })   
            </td>
            <td class="ranking">
                @Html.DisplayFor(modelItem => rank.TeamResult.PointValue)    
            </td>
            @if (Model.First().CompetitionYear == DateTime.Today.Year)
            {
                <td class="compare"><input name="team_compare" value="@Html.DisplayFor(modelitem => rank.TeamId)" type="checkbox" id="team_compare" /></td>
            }
            @{ index += 1; }
        </tr>
    }  
    <tr class="tablebottomactions">
       <td colspan="2">
            @if (Model.PageIndex > 0)
            { 
                <a class="pager" id="previous"><img src="@Url.Content("~/Content/images/return_button.png")" alt="@SharedStrings.Previous" /><span>@SharedStrings.Previous</span></a>
            }
        </td>
        <td></td>
        @if (Model.First().CompetitionYear == DateTime.Today.Year)
        { <td></td> }
        <td id="nextparent" colspan="2">
            @if (Model.HasNextPage && Model.PageIndex < Model.TotalPages)
            {
               <a class="pager" id="next"><span>@SharedStrings.Next</span><img src="@Url.Content("~/Content/images/next_button.png")" alt="@SharedStrings.Next" /></a>
            } 
        </td>
    </tr>
}
else
{ 
    <tr><td>@RankingStrings.NoRankingsFound</td></tr>
}
</table>